services:
  - type: web
    name: voterwa-app
    env: python
    buildCommand: pip install -r requirements.txt
    # Added --timeout 90 to prevent the 'Worker Timeout' error
    startCommand: gunicorn --timeout 90 app:app
    plan: free
